DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id        INT AUTO_INCREMENT PRIMARY KEY,
  username  VARCHAR(20) UNIQUE NOT NULL,
  email     VARCHAR(40) UNIQUE NOT NULL,
  password  VARCHAR(255) NOT NULL,
  created   DATETIME
);
